name: wts_bloc
description: "A new Flutter project."
publish_to: "none"

version: 1.5.0+15

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  a11y_assessments:
    path: ./a11y_assessments

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.3
  dio: ^5.6.0
  talker_dio_logger: ^4.4.1
  flutter_bloc: ^9.1.0
  talker_bloc_logger: ^4.4.1
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  carousel_slider: ^5.0.0
  syncfusion_flutter_charts: ^29.1.39
  flutter_localization: ^0.3.2
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  flutter_screenutil: ^5.9.3
  google_maps_flutter: ^2.9.0
  video_player: ^2.9.1
  smooth_page_indicator: ^1.2.0+3
  chewie: ^1.8.4
  geolocator: ^14.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  syncfusion_flutter_pdfviewer: ^29.1.39
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  flutter_widget_from_html: ^0.16.0
  equatable: ^2.0.5
  shimmer: ^3.0.0
  animate_do: ^4.2.0
  logger: ^2.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  jiffy: ^6.3.1
  open_filex: ^4.5.0
  loader_overlay: ^5.0.0
  provider: ^6.1.2
  permission_handler: ^12.0.0+1
  flutter_rounded_date_picker: ^3.0.4
  flutter_image_compress: ^2.3.0
  path: ^1.9.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/sample.pdf

  fonts:
    - family: IBMPlexSansThai
      fonts:
        - asset: assets/fonts/IBMPlexSansThai-Regular.ttf
        - asset: assets/fonts/IBMPlexSansThai-Medium.ttf
        - asset: assets/fonts/IBMPlexSansThai-Bold.ttf
          weight: 700